#ifndef LIBQCUSTOMPLOT_GLOBAL_H
#define LIBQCUSTOMPLOT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBQCUSTOMPLOT_LIBRARY)
#  define LIBQCUSTOMPLOTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBQCUSTOMPLOTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQCUSTOMPLOT_GLOBAL_H
